# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: pygments

# Title
name: The Code for Sacramento Playbook
subtitle: Code for Sacramento's Operations Manual

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/playbook'

# Author/Organization info to be displayed in the templates
author:
  name: Code for Sacramento
  url: https://code4sac.github.io/playbook

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true
- text: Example Page
  url: example_page.html
  internal: true
- text: Project Repo
  url: https://github.com/code4sac/playbook
  internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: The Code for Sacramento Playbook
  description: Code for Sacramento's Operations Manual
  url: https://github.com/code4sac/playbook

# Style Variables
brand_color: "#0080ff"
